// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/sync.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncDeltaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Delta         string                 `protobuf:"bytes,3,opt,name=delta,proto3" json:"delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDeltaRequest) Reset() {
	*x = SyncDeltaRequest{}
	mi := &file_api_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDeltaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDeltaRequest) ProtoMessage() {}

func (x *SyncDeltaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDeltaRequest.ProtoReflect.Descriptor instead.
func (*SyncDeltaRequest) Descriptor() ([]byte, []int) {
	return file_api_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncDeltaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SyncDeltaRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *SyncDeltaRequest) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

type SyncDeltaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDeltaResponse) Reset() {
	*x = SyncDeltaResponse{}
	mi := &file_api_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDeltaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDeltaResponse) ProtoMessage() {}

func (x *SyncDeltaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDeltaResponse.ProtoReflect.Descriptor instead.
func (*SyncDeltaResponse) Descriptor() ([]byte, []int) {
	return file_api_sync_proto_rawDescGZIP(), []int{1}
}

func (x *SyncDeltaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncDeltaResponse) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type GetVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionsRequest) Reset() {
	*x = GetVersionsRequest{}
	mi := &file_api_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionsRequest) ProtoMessage() {}

func (x *GetVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionsRequest.ProtoReflect.Descriptor instead.
func (*GetVersionsRequest) Descriptor() ([]byte, []int) {
	return file_api_sync_proto_rawDescGZIP(), []int{2}
}

func (x *GetVersionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetVersionsRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type GetVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VersionIds    []string               `protobuf:"bytes,1,rep,name=version_ids,json=versionIds,proto3" json:"version_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionsResponse) Reset() {
	*x = GetVersionsResponse{}
	mi := &file_api_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionsResponse) ProtoMessage() {}

func (x *GetVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionsResponse.ProtoReflect.Descriptor instead.
func (*GetVersionsResponse) Descriptor() ([]byte, []int) {
	return file_api_sync_proto_rawDescGZIP(), []int{3}
}

func (x *GetVersionsResponse) GetVersionIds() []string {
	if x != nil {
		return x.VersionIds
	}
	return nil
}

type ReplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Deltas        []string               `protobuf:"bytes,3,rep,name=deltas,proto3" json:"deltas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayRequest) Reset() {
	*x = ReplayRequest{}
	mi := &file_api_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayRequest) ProtoMessage() {}

func (x *ReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayRequest.ProtoReflect.Descriptor instead.
func (*ReplayRequest) Descriptor() ([]byte, []int) {
	return file_api_sync_proto_rawDescGZIP(), []int{4}
}

func (x *ReplayRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReplayRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *ReplayRequest) GetDeltas() []string {
	if x != nil {
		return x.Deltas
	}
	return nil
}

type ReplayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayResponse) Reset() {
	*x = ReplayResponse{}
	mi := &file_api_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayResponse) ProtoMessage() {}

func (x *ReplayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayResponse.ProtoReflect.Descriptor instead.
func (*ReplayResponse) Descriptor() ([]byte, []int) {
	return file_api_sync_proto_rawDescGZIP(), []int{5}
}

func (x *ReplayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_api_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_sync_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetStatusRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_api_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_sync_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_sync_proto protoreflect.FileDescriptor

const file_api_sync_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/sync.proto\x12\x04sync\"X\n" +
	"\x10SyncDeltaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x14\n" +
	"\x05delta\x18\x03 \x01(\tR\x05delta\"L\n" +
	"\x11SyncDeltaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\"D\n" +
	"\x12GetVersionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\"6\n" +
	"\x13GetVersionsResponse\x12\x1f\n" +
	"\vversion_ids\x18\x01 \x03(\tR\n" +
	"versionIds\"W\n" +
	"\rReplayRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x16\n" +
	"\x06deltas\x18\x03 \x03(\tR\x06deltas\"*\n" +
	"\x0eReplayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"B\n" +
	"\x10GetStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\"+\n" +
	"\x11GetStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x82\x02\n" +
	"\vSyncService\x12<\n" +
	"\tSyncDelta\x12\x16.sync.SyncDeltaRequest\x1a\x17.sync.SyncDeltaResponse\x12B\n" +
	"\vGetVersions\x12\x18.sync.GetVersionsRequest\x1a\x19.sync.GetVersionsResponse\x123\n" +
	"\x06Replay\x12\x13.sync.ReplayRequest\x1a\x14.sync.ReplayResponse\x12<\n" +
	"\tGetStatus\x12\x16.sync.GetStatusRequest\x1a\x17.sync.GetStatusResponseB\x11Z\x0fsyncservice/apib\x06proto3"

var (
	file_api_sync_proto_rawDescOnce sync.Once
	file_api_sync_proto_rawDescData []byte
)

func file_api_sync_proto_rawDescGZIP() []byte {
	file_api_sync_proto_rawDescOnce.Do(func() {
		file_api_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_sync_proto_rawDesc), len(file_api_sync_proto_rawDesc)))
	})
	return file_api_sync_proto_rawDescData
}

var file_api_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_sync_proto_goTypes = []any{
	(*SyncDeltaRequest)(nil),    // 0: sync.SyncDeltaRequest
	(*SyncDeltaResponse)(nil),   // 1: sync.SyncDeltaResponse
	(*GetVersionsRequest)(nil),  // 2: sync.GetVersionsRequest
	(*GetVersionsResponse)(nil), // 3: sync.GetVersionsResponse
	(*ReplayRequest)(nil),       // 4: sync.ReplayRequest
	(*ReplayResponse)(nil),      // 5: sync.ReplayResponse
	(*GetStatusRequest)(nil),    // 6: sync.GetStatusRequest
	(*GetStatusResponse)(nil),   // 7: sync.GetStatusResponse
}
var file_api_sync_proto_depIdxs = []int32{
	0, // 0: sync.SyncService.SyncDelta:input_type -> sync.SyncDeltaRequest
	2, // 1: sync.SyncService.GetVersions:input_type -> sync.GetVersionsRequest
	4, // 2: sync.SyncService.Replay:input_type -> sync.ReplayRequest
	6, // 3: sync.SyncService.GetStatus:input_type -> sync.GetStatusRequest
	1, // 4: sync.SyncService.SyncDelta:output_type -> sync.SyncDeltaResponse
	3, // 5: sync.SyncService.GetVersions:output_type -> sync.GetVersionsResponse
	5, // 6: sync.SyncService.Replay:output_type -> sync.ReplayResponse
	7, // 7: sync.SyncService.GetStatus:output_type -> sync.GetStatusResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_sync_proto_init() }
func file_api_sync_proto_init() {
	if File_api_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_sync_proto_rawDesc), len(file_api_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sync_proto_goTypes,
		DependencyIndexes: file_api_sync_proto_depIdxs,
		MessageInfos:      file_api_sync_proto_msgTypes,
	}.Build()
	File_api_sync_proto = out.File
	file_api_sync_proto_goTypes = nil
	file_api_sync_proto_depIdxs = nil
}
