// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/conflict.proto

package conflictpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveConflictRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Section       string                 `protobuf:"bytes,3,opt,name=section,proto3" json:"section,omitempty"` // 段落/欄位
	Delta         string                 `protobuf:"bytes,4,opt,name=delta,proto3" json:"delta,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveConflictRequest) Reset() {
	*x = ResolveConflictRequest{}
	mi := &file_api_conflict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveConflictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveConflictRequest) ProtoMessage() {}

func (x *ResolveConflictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conflict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveConflictRequest.ProtoReflect.Descriptor instead.
func (*ResolveConflictRequest) Descriptor() ([]byte, []int) {
	return file_api_conflict_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveConflictRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResolveConflictRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *ResolveConflictRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *ResolveConflictRequest) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *ResolveConflictRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ResolveConflictResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resolved      bool                   `protobuf:"varint,1,opt,name=resolved,proto3" json:"resolved,omitempty"`
	MergedContent string                 `protobuf:"bytes,2,opt,name=merged_content,json=mergedContent,proto3" json:"merged_content,omitempty"`
	ConflictId    string                 `protobuf:"bytes,3,opt,name=conflict_id,json=conflictId,proto3" json:"conflict_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveConflictResponse) Reset() {
	*x = ResolveConflictResponse{}
	mi := &file_api_conflict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveConflictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveConflictResponse) ProtoMessage() {}

func (x *ResolveConflictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_conflict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveConflictResponse.ProtoReflect.Descriptor instead.
func (*ResolveConflictResponse) Descriptor() ([]byte, []int) {
	return file_api_conflict_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveConflictResponse) GetResolved() bool {
	if x != nil {
		return x.Resolved
	}
	return false
}

func (x *ResolveConflictResponse) GetMergedContent() string {
	if x != nil {
		return x.MergedContent
	}
	return ""
}

func (x *ResolveConflictResponse) GetConflictId() string {
	if x != nil {
		return x.ConflictId
	}
	return ""
}

func (x *ResolveConflictResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetConflictStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Section       string                 `protobuf:"bytes,3,opt,name=section,proto3" json:"section,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConflictStatusRequest) Reset() {
	*x = GetConflictStatusRequest{}
	mi := &file_api_conflict_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConflictStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConflictStatusRequest) ProtoMessage() {}

func (x *GetConflictStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conflict_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConflictStatusRequest.ProtoReflect.Descriptor instead.
func (*GetConflictStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_conflict_proto_rawDescGZIP(), []int{2}
}

func (x *GetConflictStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetConflictStatusRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *GetConflictStatusRequest) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

type GetConflictStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasConflict   bool                   `protobuf:"varint,1,opt,name=has_conflict,json=hasConflict,proto3" json:"has_conflict,omitempty"`
	ConflictId    string                 `protobuf:"bytes,2,opt,name=conflict_id,json=conflictId,proto3" json:"conflict_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConflictStatusResponse) Reset() {
	*x = GetConflictStatusResponse{}
	mi := &file_api_conflict_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConflictStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConflictStatusResponse) ProtoMessage() {}

func (x *GetConflictStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_conflict_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConflictStatusResponse.ProtoReflect.Descriptor instead.
func (*GetConflictStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_conflict_proto_rawDescGZIP(), []int{3}
}

func (x *GetConflictStatusResponse) GetHasConflict() bool {
	if x != nil {
		return x.HasConflict
	}
	return false
}

func (x *GetConflictStatusResponse) GetConflictId() string {
	if x != nil {
		return x.ConflictId
	}
	return ""
}

func (x *GetConflictStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetConflictStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListConflictsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConflictsRequest) Reset() {
	*x = ListConflictsRequest{}
	mi := &file_api_conflict_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConflictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConflictsRequest) ProtoMessage() {}

func (x *ListConflictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_conflict_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConflictsRequest.ProtoReflect.Descriptor instead.
func (*ListConflictsRequest) Descriptor() ([]byte, []int) {
	return file_api_conflict_proto_rawDescGZIP(), []int{4}
}

func (x *ListConflictsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListConflictsRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type ListConflictsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conflicts     []*ConflictInfo        `protobuf:"bytes,1,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConflictsResponse) Reset() {
	*x = ListConflictsResponse{}
	mi := &file_api_conflict_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConflictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConflictsResponse) ProtoMessage() {}

func (x *ListConflictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_conflict_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConflictsResponse.ProtoReflect.Descriptor instead.
func (*ListConflictsResponse) Descriptor() ([]byte, []int) {
	return file_api_conflict_proto_rawDescGZIP(), []int{5}
}

func (x *ListConflictsResponse) GetConflicts() []*ConflictInfo {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type ConflictInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConflictId    string                 `protobuf:"bytes,1,opt,name=conflict_id,json=conflictId,proto3" json:"conflict_id,omitempty"`
	DocId         string                 `protobuf:"bytes,2,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Section       string                 `protobuf:"bytes,3,opt,name=section,proto3" json:"section,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConflictInfo) Reset() {
	*x = ConflictInfo{}
	mi := &file_api_conflict_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictInfo) ProtoMessage() {}

func (x *ConflictInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_conflict_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictInfo.ProtoReflect.Descriptor instead.
func (*ConflictInfo) Descriptor() ([]byte, []int) {
	return file_api_conflict_proto_rawDescGZIP(), []int{6}
}

func (x *ConflictInfo) GetConflictId() string {
	if x != nil {
		return x.ConflictId
	}
	return ""
}

func (x *ConflictInfo) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *ConflictInfo) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *ConflictInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConflictInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_api_conflict_proto protoreflect.FileDescriptor

const file_api_conflict_proto_rawDesc = "" +
	"\n" +
	"\x12api/conflict.proto\x12\bconflict\"\x92\x01\n" +
	"\x16ResolveConflictRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x18\n" +
	"\asection\x18\x03 \x01(\tR\asection\x12\x14\n" +
	"\x05delta\x18\x04 \x01(\tR\x05delta\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"\x97\x01\n" +
	"\x17ResolveConflictResponse\x12\x1a\n" +
	"\bresolved\x18\x01 \x01(\bR\bresolved\x12%\n" +
	"\x0emerged_content\x18\x02 \x01(\tR\rmergedContent\x12\x1f\n" +
	"\vconflict_id\x18\x03 \x01(\tR\n" +
	"conflictId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"d\n" +
	"\x18GetConflictStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x18\n" +
	"\asection\x18\x03 \x01(\tR\asection\"\x91\x01\n" +
	"\x19GetConflictStatusResponse\x12!\n" +
	"\fhas_conflict\x18\x01 \x01(\bR\vhasConflict\x12\x1f\n" +
	"\vconflict_id\x18\x02 \x01(\tR\n" +
	"conflictId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"F\n" +
	"\x14ListConflictsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\"M\n" +
	"\x15ListConflictsResponse\x124\n" +
	"\tconflicts\x18\x01 \x03(\v2\x16.conflict.ConflictInfoR\tconflicts\"\x97\x01\n" +
	"\fConflictInfo\x12\x1f\n" +
	"\vconflict_id\x18\x01 \x01(\tR\n" +
	"conflictId\x12\x15\n" +
	"\x06doc_id\x18\x02 \x01(\tR\x05docId\x12\x18\n" +
	"\asection\x18\x03 \x01(\tR\asection\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt2\x99\x02\n" +
	"\x0fConflictService\x12V\n" +
	"\x0fResolveConflict\x12 .conflict.ResolveConflictRequest\x1a!.conflict.ResolveConflictResponse\x12\\\n" +
	"\x11GetConflictStatus\x12\".conflict.GetConflictStatusRequest\x1a#.conflict.GetConflictStatusResponse\x12P\n" +
	"\rListConflicts\x12\x1e.conflict.ListConflictsRequest\x1a\x1f.conflict.ListConflictsResponseB\x12Z\x10./api;conflictpbb\x06proto3"

var (
	file_api_conflict_proto_rawDescOnce sync.Once
	file_api_conflict_proto_rawDescData []byte
)

func file_api_conflict_proto_rawDescGZIP() []byte {
	file_api_conflict_proto_rawDescOnce.Do(func() {
		file_api_conflict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_conflict_proto_rawDesc), len(file_api_conflict_proto_rawDesc)))
	})
	return file_api_conflict_proto_rawDescData
}

var file_api_conflict_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_conflict_proto_goTypes = []any{
	(*ResolveConflictRequest)(nil),    // 0: conflict.ResolveConflictRequest
	(*ResolveConflictResponse)(nil),   // 1: conflict.ResolveConflictResponse
	(*GetConflictStatusRequest)(nil),  // 2: conflict.GetConflictStatusRequest
	(*GetConflictStatusResponse)(nil), // 3: conflict.GetConflictStatusResponse
	(*ListConflictsRequest)(nil),      // 4: conflict.ListConflictsRequest
	(*ListConflictsResponse)(nil),     // 5: conflict.ListConflictsResponse
	(*ConflictInfo)(nil),              // 6: conflict.ConflictInfo
}
var file_api_conflict_proto_depIdxs = []int32{
	6, // 0: conflict.ListConflictsResponse.conflicts:type_name -> conflict.ConflictInfo
	0, // 1: conflict.ConflictService.ResolveConflict:input_type -> conflict.ResolveConflictRequest
	2, // 2: conflict.ConflictService.GetConflictStatus:input_type -> conflict.GetConflictStatusRequest
	4, // 3: conflict.ConflictService.ListConflicts:input_type -> conflict.ListConflictsRequest
	1, // 4: conflict.ConflictService.ResolveConflict:output_type -> conflict.ResolveConflictResponse
	3, // 5: conflict.ConflictService.GetConflictStatus:output_type -> conflict.GetConflictStatusResponse
	5, // 6: conflict.ConflictService.ListConflicts:output_type -> conflict.ListConflictsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_conflict_proto_init() }
func file_api_conflict_proto_init() {
	if File_api_conflict_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_conflict_proto_rawDesc), len(file_api_conflict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_conflict_proto_goTypes,
		DependencyIndexes: file_api_conflict_proto_depIdxs,
		MessageInfos:      file_api_conflict_proto_msgTypes,
	}.Build()
	File_api_conflict_proto = out.File
	file_api_conflict_proto_goTypes = nil
	file_api_conflict_proto_depIdxs = nil
}
