// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/conflict.proto

package conflictpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConflictService_ResolveConflict_FullMethodName   = "/conflict.ConflictService/ResolveConflict"
	ConflictService_GetConflictStatus_FullMethodName = "/conflict.ConflictService/GetConflictStatus"
	ConflictService_ListConflicts_FullMethodName     = "/conflict.ConflictService/ListConflicts"
)

// ConflictServiceClient is the client API for ConflictService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConflictServiceClient interface {
	ResolveConflict(ctx context.Context, in *ResolveConflictRequest, opts ...grpc.CallOption) (*ResolveConflictResponse, error)
	GetConflictStatus(ctx context.Context, in *GetConflictStatusRequest, opts ...grpc.CallOption) (*GetConflictStatusResponse, error)
	ListConflicts(ctx context.Context, in *ListConflictsRequest, opts ...grpc.CallOption) (*ListConflictsResponse, error)
}

type conflictServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConflictServiceClient(cc grpc.ClientConnInterface) ConflictServiceClient {
	return &conflictServiceClient{cc}
}

func (c *conflictServiceClient) ResolveConflict(ctx context.Context, in *ResolveConflictRequest, opts ...grpc.CallOption) (*ResolveConflictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveConflictResponse)
	err := c.cc.Invoke(ctx, ConflictService_ResolveConflict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conflictServiceClient) GetConflictStatus(ctx context.Context, in *GetConflictStatusRequest, opts ...grpc.CallOption) (*GetConflictStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConflictStatusResponse)
	err := c.cc.Invoke(ctx, ConflictService_GetConflictStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conflictServiceClient) ListConflicts(ctx context.Context, in *ListConflictsRequest, opts ...grpc.CallOption) (*ListConflictsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConflictsResponse)
	err := c.cc.Invoke(ctx, ConflictService_ListConflicts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConflictServiceServer is the server API for ConflictService service.
// All implementations must embed UnimplementedConflictServiceServer
// for forward compatibility.
type ConflictServiceServer interface {
	ResolveConflict(context.Context, *ResolveConflictRequest) (*ResolveConflictResponse, error)
	GetConflictStatus(context.Context, *GetConflictStatusRequest) (*GetConflictStatusResponse, error)
	ListConflicts(context.Context, *ListConflictsRequest) (*ListConflictsResponse, error)
	mustEmbedUnimplementedConflictServiceServer()
}

// UnimplementedConflictServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConflictServiceServer struct{}

func (UnimplementedConflictServiceServer) ResolveConflict(context.Context, *ResolveConflictRequest) (*ResolveConflictResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveConflict not implemented")
}
func (UnimplementedConflictServiceServer) GetConflictStatus(context.Context, *GetConflictStatusRequest) (*GetConflictStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConflictStatus not implemented")
}
func (UnimplementedConflictServiceServer) ListConflicts(context.Context, *ListConflictsRequest) (*ListConflictsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConflicts not implemented")
}
func (UnimplementedConflictServiceServer) mustEmbedUnimplementedConflictServiceServer() {}
func (UnimplementedConflictServiceServer) testEmbeddedByValue()                         {}

// UnsafeConflictServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConflictServiceServer will
// result in compilation errors.
type UnsafeConflictServiceServer interface {
	mustEmbedUnimplementedConflictServiceServer()
}

func RegisterConflictServiceServer(s grpc.ServiceRegistrar, srv ConflictServiceServer) {
	// If the following call pancis, it indicates UnimplementedConflictServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConflictService_ServiceDesc, srv)
}

func _ConflictService_ResolveConflict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveConflictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConflictServiceServer).ResolveConflict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConflictService_ResolveConflict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConflictServiceServer).ResolveConflict(ctx, req.(*ResolveConflictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConflictService_GetConflictStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConflictStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConflictServiceServer).GetConflictStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConflictService_GetConflictStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConflictServiceServer).GetConflictStatus(ctx, req.(*GetConflictStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConflictService_ListConflicts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConflictsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConflictServiceServer).ListConflicts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConflictService_ListConflicts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConflictServiceServer).ListConflicts(ctx, req.(*ListConflictsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConflictService_ServiceDesc is the grpc.ServiceDesc for ConflictService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConflictService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conflict.ConflictService",
	HandlerType: (*ConflictServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveConflict",
			Handler:    _ConflictService_ResolveConflict_Handler,
		},
		{
			MethodName: "GetConflictStatus",
			Handler:    _ConflictService_GetConflictStatus_Handler,
		},
		{
			MethodName: "ListConflicts",
			Handler:    _ConflictService_ListConflicts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/conflict.proto",
}
